import { Injectable } from '@nestjs/common';
import { User } from 'src/interfaces/user/user.interface';
import { Alignment, Gender } from 'src/Enums/charatcer/character.enums';
import { CharacterSheet } from 'src/interfaces/character/character.interface';
import { SkillName, Skill } from 'src/interfaces/character/skills.interface';
import { AbilityType } from 'src/Enums/abilities/abilities.enums';

@Injectable()
export class CharacterRepository {
  private mockCharacter: CharacterSheet[] = [
    {
      id: 'test1b',
      discordUserId: '295061081565560832',
      ECL: 3,
      characterName: 'Test Character',
      characterLastName: 'Doe',
      playerName: 'John',
      homeland: 'Elven Forest',
      raceId: 'elf123',
      type: 'Elf',
      gender: Gender.Female,
      alignment: Alignment.N, // Cast to Alignment if needed
      deity: 'Corellon',
      age: 120,
      weight: 65,
      skin: 'Fair',
      hair: 'Silver',
      eyes: 'Green',
      equipmentId: 'eq123',
      abilityScores: {
        STR: {
          total: 14,
          base: 14,
          miscellaneous: 0,
          race: 0,
          equipment: 0,
          note: '',
          abilityModifier: 2,
        },
        DEX: {
          total: 15,
          base: 15,
          miscellaneous: 0,
          race: 2,
          equipment: 0,
          note: '',
          abilityModifier: 2,
        },
        CON: {
          total: 12,
          base: 12,
          miscellaneous: 0,
          race: 0,
          equipment: 0,
          note: '',
          abilityModifier: 1,
        },
        INT: {
          total: 14,
          base: 14,
          miscellaneous: 0,
          race: 0,
          equipment: 0,
          note: '',
          abilityModifier: 2,
        },
        WIS: {
          total: 13,
          base: 13,
          miscellaneous: 0,
          race: 0,
          equipment: 0,
          note: '',
          abilityModifier: 1,
        },
        CHA: {
          total: 10,
          base: 10,
          miscellaneous: 0,
          race: 0,
          equipment: 0,
          note: '',
          abilityModifier: 0,
        },
      },
      saves: {
        fortitude: {
          total: 4,
          baseSave: 3,
          abilityModifier: 1,
          epicSaveBonus: 0,
          miscellaneous: 0,
          temporaryModifier: 0,
          raceModifier: 0,
          conditional: [],
          note: '',
        },
        reflex: {
          total: 6,
          baseSave: 3,
          abilityModifier: 2,
          epicSaveBonus: 0,
          miscellaneous: 1,
          temporaryModifier: 0,
          raceModifier: 0,
          conditional: [],
          note: '',
        },
        will: {
          total: 4,
          baseSave: 2,
          abilityModifier: 1,
          epicSaveBonus: 0,
          miscellaneous: 1,
          temporaryModifier: 0,
          raceModifier: 0,
          conditional: [],
          note: '',
        },
      },
      spellResist: 0,
      powerResist: 0,
      arcaneSpellFailure: 10,
      baseAttack: 2,
      attackAbilityModifier: 'STR',
      skills: {
        appraise: {
          name: 'Appraise',
          ranks: 0,
          modifier: 'INT',
          proficiency: false,
          raceBonus: 0,
          micBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        balance: {
          name: 'Balance',
          ranks: 0,
          modifier: 'INT',
          proficiency: false,
          raceBonus: 0,
          micBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        bluff: {
          name: 'Bluff',
          ranks: 0,
          modifier: 'INT',
          proficiency: false,
          raceBonus: 0,
          micBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        climb: {
          name: 'Climb',
          ranks: 0,
          modifier: 'INT',
          proficiency: false,
          raceBonus: 0,
          micBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        concentration: {
          name: 'Concentration',
          ranks: 0,
          modifier: 'INT',
          proficiency: false,
          raceBonus: 0,
          micBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        craft: {
          name: 'Craft',
          ranks: 0,
          modifier: 'INT',
          proficiency: false,
          raceBonus: 0,
          micBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        decipherScript: {
          name: 'Decipher Script',
          ranks: 0,
          modifier: 'INT',
          proficiency: false,
          raceBonus: 0,
          micBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        diplomacy: {
          name: 'Diplomacy',
          ranks: 0,
          modifier: 'INT',
          proficiency: false,
          raceBonus: 0,
          micBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        disableDevice: {
          name: 'Disable Device',
          ranks: 0,
          modifier: 'INT',
          proficiency: false,
          raceBonus: 0,
          micBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        disguise: {
          name: 'Disguise',
          ranks: 0,
          modifier: 'INT',
          proficiency: false,
          raceBonus: 0,
          micBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        escapeArtist: {
          name: 'Escape Artist',
          ranks: 0,
          modifier: 'INT',
          proficiency: false,
          raceBonus: 0,
          micBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        forgery: {
          name: 'Forgery',
          ranks: 0,
          modifier: 'INT',
          proficiency: false,
          raceBonus: 0,
          micBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        gatherInformation: {
          name: 'Gather Information',
          ranks: 0,
          modifier: 'INT',
          proficiency: false,
          raceBonus: 0,
          micBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        handleAnimal: {
          name: 'Handle Animal',
          ranks: 0,
          modifier: 'INT',
          proficiency: false,
          raceBonus: 0,
          micBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        heal: {
          name: 'Heal',
          ranks: 0,
          modifier: 'INT',
          proficiency: false,
          raceBonus: 0,
          micBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        hide: {
          name: 'Hide',
          ranks: 0,
          modifier: 'INT',
          proficiency: false,
          raceBonus: 0,
          micBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        intimidate: {
          name: 'Intimidate',
          ranks: 0,
          modifier: 'INT',
          proficiency: false,
          raceBonus: 0,
          micBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        jump: {
          name: 'Jump',
          ranks: 0,
          modifier: 'INT',
          proficiency: false,
          raceBonus: 0,
          micBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        knowledgeArcana: {
          name: 'Knowledge (arcana)',
          ranks: 0,
          modifier: 'INT',
          proficiency: false,
          raceBonus: 0,
          micBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        knowledgeArchitecture: {
          name: 'Knowledge (architecture and engineering)',
          ranks: 0,
          modifier: 'INT',
          proficiency: false,
          raceBonus: 0,
          micBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        knowledgedungeoneering: {
          name: 'Knowledge (dungeoneering)',
          ranks: 0,
          modifier: 'INT',
          proficiency: false,
          raceBonus: 0,
          micBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        knowledgeGeography: {
          name: 'Knowledge (geography)',
          ranks: 0,
          modifier: 'INT',
          proficiency: false,
          raceBonus: 0,
          micBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        knowledgeHistory: {
          name: 'Knowledge (history)',
          ranks: 0,
          modifier: 'INT',
          proficiency: false,
          raceBonus: 0,
          micBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        knowledgeLocal: {
          name: 'Knowledge (local)',
          ranks: 0,
          modifier: 'INT',
          proficiency: false,
          raceBonus: 0,
          micBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        knowledgeNature: {
          name: 'Knowledge (nature)',
          ranks: 0,
          modifier: 'INT',
          proficiency: false,
          raceBonus: 0,
          micBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        knowledgeNobility: {
          name: 'Knowledge (nobility and royalty)',
          ranks: 0,
          modifier: 'INT',
          proficiency: false,
          raceBonus: 0,
          micBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        knowledgeReligion: {
          name: 'Knowledge (religion)',
          ranks: 0,
          modifier: 'INT',
          proficiency: false,
          raceBonus: 0,
          micBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        knowledgePlanes: {
          name: 'Knowledge (the planes)',
          ranks: 0,
          modifier: 'INT',
          proficiency: false,
          raceBonus: 0,
          micBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        listen: {
          name: 'Listen',
          ranks: 0,
          modifier: 'INT',
          proficiency: false,
          raceBonus: 0,
          micBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        moveSilently: {
          name: 'Move Silently',
          ranks: 0,
          modifier: 'INT',
          proficiency: false,
          raceBonus: 0,
          micBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        openLock: {
          name: 'Open Lock',
          ranks: 0,
          modifier: 'INT',
          proficiency: false,
          raceBonus: 0,
          micBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        perform: {
          name: 'Perform',
          ranks: 0,
          modifier: 'INT',
          proficiency: false,
          raceBonus: 0,
          micBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        profession: {
          name: 'Profession',
          ranks: 0,
          modifier: 'INT',
          proficiency: false,
          raceBonus: 0,
          micBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        ride: {
          name: 'Ride',
          ranks: 0,
          modifier: 'INT',
          proficiency: false,
          raceBonus: 0,
          micBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        search: {
          name: 'Search',
          ranks: 0,
          modifier: 'INT',
          proficiency: false,
          raceBonus: 0,
          micBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        senseMotive: {
          name: 'Sense Motive',
          ranks: 0,
          modifier: 'INT',
          proficiency: false,
          raceBonus: 0,
          micBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        sleightHand: {
          name: 'Sleight of Hand',
          ranks: 0,
          modifier: 'INT',
          proficiency: false,
          raceBonus: 0,
          micBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        speakLanguage: {
          name: 'Speak Language',
          ranks: 0,
          modifier: 'INT',
          proficiency: false,
          raceBonus: 0,
          micBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        spellcraft: {
          name: 'Spellcraf',
          ranks: 0,
          modifier: 'INT',
          proficiency: false,
          raceBonus: 0,
          micBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        spot: {
          name: 'Spot',
          ranks: 0,
          modifier: 'INT',
          proficiency: false,
          raceBonus: 0,
          micBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        survival: {
          name: 'Survival',
          ranks: 0,
          modifier: 'INT',
          proficiency: false,
          raceBonus: 0,
          micBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        swim: {
          name: 'Swim',
          ranks: 0,
          modifier: 'INT',
          proficiency: false,
          raceBonus: 0,
          micBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        tumble: {
          name: 'Tumble',
          ranks: 0,
          modifier: 'INT',
          proficiency: false,
          raceBonus: 0,
          micBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        useMagicDevice: {
          name: 'Use Magic Device',
          ranks: 0,
          modifier: 'INT',
          proficiency: false,
          raceBonus: 0,
          micBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        useRope: {
          name: 'Use Rope',
          ranks: 0,
          modifier: 'INT',
          proficiency: false,
          raceBonus: 0,
          micBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
      },
      weapons: [
        {
          id: '1',
          createdBy: 'user1',
          name: 'Long Sword',
          cost: 150,
          damageDiceType: 8,
          damageDiceCount: 1,
          criticalRange: 19,
          range: 0,
          weight: 3,
          damageType: 'Slashing',
          weaponType: 'Simple',
          weaponEnhancement: 0,
          weaponFocus: 0,
          weaponSpecialization: 0,
          ammunition: 0,
          damageAbility: AbilityType.STR,
        },
        {
          id: '2',
          createdBy: 'user2',
          name: 'Crossbow',
          cost: 250,
          damageDiceType: 10,
          damageDiceCount: 1,
          criticalRange: 20,
          range: 80,
          weight: 5,
          damageType: 'Pircing',
          weaponType: 'Simple',
          weaponEnhancement: 0,
          weaponFocus: 0,
          weaponSpecialization: 0,
          ammunition: 20,
          damageAbility: AbilityType.NONE,
        },
      ],
      activeWeapon: '1',
    },
  ];

  async findCharacter(characterId: string): Promise<CharacterSheet> {
    return this.mockCharacter.find((char) => char.id === characterId);
  }

  async findAllUserCharacters(userId: string): Promise<CharacterSheet[]> {
    const characters = this.mockCharacter.filter(
      (character) => character.discordUserId === userId,
    );
    return characters;
  }
}
