import { Injectable } from '@nestjs/common';
import { AbilityType } from 'src/Enums/abilities/abilities.enums';
import {
  SkillSheet,
  Skill,
  SkillName,
} from 'src/interfaces/skills/skills.interface';

@Injectable()
export class SkillsRepository {
  private mockSkills: SkillSheet[] = [
    {
      id: '1',
      characterId: 'test1b',
      skills: {
        appraise: {
          name: 'Appraise',
          ranks: 0,
          modifier: AbilityType.INT,
          proficiency: false,
          racialBonus: 0,
          miscBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        balance: {
          name: 'Balance',
          ranks: 0,
          modifier: AbilityType.INT,
          proficiency: false,
          racialBonus: 0,
          miscBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        bluff: {
          name: 'Bluff',
          ranks: 0,
          modifier: AbilityType.INT,
          proficiency: false,
          racialBonus: 0,
          miscBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        climb: {
          name: 'Climb',
          ranks: 0,
          modifier: AbilityType.INT,
          proficiency: false,
          racialBonus: 0,
          miscBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        concentration: {
          name: 'Concentration',
          ranks: 0,
          modifier: AbilityType.INT,
          proficiency: false,
          racialBonus: 0,
          miscBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        craft: {
          name: 'Craft',
          ranks: 0,
          modifier: AbilityType.INT,
          proficiency: false,
          racialBonus: 0,
          miscBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        decipherScript: {
          name: 'Decipher Script',
          ranks: 0,
          modifier: AbilityType.INT,
          proficiency: false,
          racialBonus: 0,
          miscBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        diplomacy: {
          name: 'Diplomacy',
          ranks: 0,
          modifier: AbilityType.INT,
          proficiency: false,
          racialBonus: 0,
          miscBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        disableDevice: {
          name: 'Disable Device',
          ranks: 0,
          modifier: AbilityType.INT,
          proficiency: false,
          racialBonus: 0,
          miscBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        disguise: {
          name: 'Disguise',
          ranks: 0,
          modifier: AbilityType.INT,
          proficiency: false,
          racialBonus: 0,
          miscBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        escapeArtist: {
          name: 'Escape Artist',
          ranks: 0,
          modifier: AbilityType.INT,
          proficiency: false,
          racialBonus: 0,
          miscBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        forgery: {
          name: 'Forgery',
          ranks: 0,
          modifier: AbilityType.INT,
          proficiency: false,
          racialBonus: 0,
          miscBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        gatherInformation: {
          name: 'Gather Information',
          ranks: 0,
          modifier: AbilityType.INT,
          proficiency: false,
          racialBonus: 0,
          miscBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        handleAnimal: {
          name: 'Handle Animal',
          ranks: 0,
          modifier: AbilityType.INT,
          proficiency: false,
          racialBonus: 0,
          miscBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        heal: {
          name: 'Heal',
          ranks: 0,
          modifier: AbilityType.INT,
          proficiency: false,
          racialBonus: 0,
          miscBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        hide: {
          name: 'Hide',
          ranks: 0,
          modifier: AbilityType.INT,
          proficiency: false,
          racialBonus: 0,
          miscBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        intimidate: {
          name: 'Intimidate',
          ranks: 0,
          modifier: AbilityType.INT,
          proficiency: false,
          racialBonus: 0,
          miscBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        jump: {
          name: 'Jump',
          ranks: 0,
          modifier: AbilityType.INT,
          proficiency: false,
          racialBonus: 0,
          miscBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        knowledgeArcana: {
          name: 'Knowledge (arcana)',
          ranks: 0,
          modifier: AbilityType.INT,
          proficiency: false,
          racialBonus: 0,
          miscBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        knowledgeArchitecture: {
          name: 'Knowledge (architecture and engineering)',
          ranks: 0,
          modifier: AbilityType.INT,
          proficiency: false,
          racialBonus: 0,
          miscBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        knowledgedungeoneering: {
          name: 'Knowledge (dungeoneering)',
          ranks: 0,
          modifier: AbilityType.INT,
          proficiency: false,
          racialBonus: 0,
          miscBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        knowledgeGeography: {
          name: 'Knowledge (geography)',
          ranks: 0,
          modifier: AbilityType.INT,
          proficiency: false,
          racialBonus: 0,
          miscBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        knowledgeHistory: {
          name: 'Knowledge (history)',
          ranks: 0,
          modifier: AbilityType.INT,
          proficiency: false,
          racialBonus: 0,
          miscBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        knowledgeLocal: {
          name: 'Knowledge (local)',
          ranks: 0,
          modifier: AbilityType.INT,
          proficiency: false,
          racialBonus: 0,
          miscBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        knowledgeNature: {
          name: 'Knowledge (nature)',
          ranks: 0,
          modifier: AbilityType.INT,
          proficiency: false,
          racialBonus: 0,
          miscBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        knowledgeNobility: {
          name: 'Knowledge (nobility and royalty)',
          ranks: 0,
          modifier: AbilityType.INT,
          proficiency: false,
          racialBonus: 0,
          miscBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        knowledgeReligion: {
          name: 'Knowledge (religion)',
          ranks: 0,
          modifier: AbilityType.INT,
          proficiency: false,
          racialBonus: 0,
          miscBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        knowledgePlanes: {
          name: 'Knowledge (the planes)',
          ranks: 0,
          modifier: AbilityType.INT,
          proficiency: false,
          racialBonus: 0,
          miscBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        listen: {
          name: 'Listen',
          ranks: 0,
          modifier: AbilityType.INT,
          proficiency: false,
          racialBonus: 0,
          miscBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        moveSilently: {
          name: 'Move Silently',
          ranks: 0,
          modifier: AbilityType.INT,
          proficiency: false,
          racialBonus: 0,
          miscBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        openLock: {
          name: 'Open Lock',
          ranks: 0,
          modifier: AbilityType.INT,
          proficiency: false,
          racialBonus: 0,
          miscBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        perform: {
          name: 'Perform',
          ranks: 0,
          modifier: AbilityType.INT,
          proficiency: false,
          racialBonus: 0,
          miscBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        profession: {
          name: 'Profession',
          ranks: 0,
          modifier: AbilityType.INT,
          proficiency: false,
          racialBonus: 0,
          miscBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        ride: {
          name: 'Ride',
          ranks: 0,
          modifier: AbilityType.INT,
          proficiency: false,
          racialBonus: 0,
          miscBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        search: {
          name: 'Search',
          ranks: 0,
          modifier: AbilityType.INT,
          proficiency: false,
          racialBonus: 0,
          miscBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        senseMotive: {
          name: 'Sense Motive',
          ranks: 0,
          modifier: AbilityType.INT,
          proficiency: false,
          racialBonus: 0,
          miscBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        sleightHand: {
          name: 'Sleight of Hand',
          ranks: 0,
          modifier: AbilityType.INT,
          proficiency: false,
          racialBonus: 0,
          miscBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        speakLanguage: {
          name: 'Speak Language',
          ranks: 0,
          modifier: AbilityType.INT,
          proficiency: false,
          racialBonus: 0,
          miscBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        spellcraft: {
          name: 'Spellcraf',
          ranks: 0,
          modifier: AbilityType.INT,
          proficiency: false,
          racialBonus: 0,
          miscBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        spot: {
          name: 'Spot',
          ranks: 0,
          modifier: AbilityType.INT,
          proficiency: false,
          racialBonus: 0,
          miscBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        survival: {
          name: 'Survival',
          ranks: 0,
          modifier: AbilityType.INT,
          proficiency: false,
          racialBonus: 0,
          miscBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        swim: {
          name: 'Swim',
          ranks: 0,
          modifier: AbilityType.INT,
          proficiency: false,
          racialBonus: 0,
          miscBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        tumble: {
          name: 'Tumble',
          ranks: 0,
          modifier: AbilityType.INT,
          proficiency: false,
          racialBonus: 0,
          miscBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        useMagicDevice: {
          name: 'Use Magic Device',
          ranks: 0,
          modifier: AbilityType.INT,
          proficiency: false,
          racialBonus: 0,
          miscBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
        useRope: {
          name: 'Use Rope',
          ranks: 0,
          modifier: AbilityType.INT,
          proficiency: false,
          racialBonus: 0,
          miscBonus: 0,
          description: 'Ability to appraise value of objects.',
        },
      },
    },
  ];
}
